services:
  claude-code:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claude-code-dev
    privileged: true  # Required for Docker-in-Docker
    volumes:
      # Mount Docker socket for Docker-in-Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount workspace for persistent development
      - ./workspace:/workspace
      # Mount home directory for Claude user
      - claude-home:/home/claude
      # Optional: Mount host's .claude config (read-only)
      - ${HOME}/.claude:/home/claude/.claude:ro
    ports:
      - "3000:3000"
      - "8080:8080"
      - "2376:2376"  # Docker daemon port
    environment:
      - CLAUDE_API_KEY=${CLAUDE_API_KEY:-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - NODE_ENV=development
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - claude-network

  # Alternative DinD setup (comment out the above and use this if socket mounting doesn't work)
  claude-code-dind:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claude-code-dind
    privileged: true
    volumes:
      - ./workspace:/workspace
      - claude-home-dind:/home/claude
      - docker-data:/var/lib/docker
    ports:
      - "3001:3000"
      - "8081:8080"
    environment:
      - CLAUDE_API_KEY=${CLAUDE_API_KEY:-}
      - DOCKER_TLS_CERTDIR=""
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - claude-network
    profiles:
      - dind  # Use with: docker-compose --profile dind up

volumes:
  claude-home:
  claude-home-dind:
  docker-data:

networks:
  claude-network:
    driver: bridge